theme: jekyll-theme-cayman
title: "Andy Hameed"
description: Welcome to my sandbox projects page. As with any sandbox, this page contains coding projects for experimentation and learning purposes. These were completed without the use of any front-end frameworks or external APIs, for the sake of learning the fundamentals of frontend development. Any images included have been created by myself using Adobe Illustrator (Ex. The pen in Live Pen tool).
